# LeafRank exemplary running case

This script contains an exemplary running case for LeafRank.

## Initialization

```{r}
####### Loading necessary script ###################
source('R/tree_utils.R')
source('R/fitness_inference.R')
source('R/solve_density.R')
source('R/message_passing.R')
library(ape)
####### Parallelize to accelerate computing ########
library(doParallel)
library(foreach)
cn <- parallel::detectCores()  
cl <- makeCluster(2)        # When cn = 20, the following script can finished in 10 mins.
registerDoParallel(cl)
```

## LeafRank Prediction

### Loading the tree

```{r}
tree_file <- "Exemplary Trees/Exemplary_Tree_SIM.rds"
phy <- readRDS(tree_file)
subsample_size <- 5
idx <- sample(phy$tip.label, subsample_size)
phy <- keep.tip(phy,idx)
```

### Initialize parameters

```{r}
################ parameter configuration ########################## 
# Simulation configuration
rho        <- subsample_size/1000000   # sampling probability  
b_rates    <- 0.2*1.2^(0:7)            # birth rates  
d_rates    <- replicate(8, 0.18)       # death rates
nu         <- replicate(8, 0.0001)     # driver mutation rates
time_scale <- 1                        # time scale
# Practical configuration
#rho        <- 0.0005       #0.0005 # sampling probability
#b_rates    <- 1.1*1.1^(0:15)   #comma seperated   16 types (1.1*1.1^0:15) 
#d_rates <- replicate(16, 1)    #comma seperated
#nu <- replicate(16, 0.0001)
#param <- get_full_pars(b_rates = b_rates, d_rates = d_rates, nu = mu, rho = rho, tree = phy, model = 'default') # model in {'default', 'agressive2', 'agressive4', 'agressive6'}
################  ODE integration setting  ######################
d_t        <- 0.01                     # delta t
timeFrom   <- 0
timeTo     <- ceiling(max(get_depth(phy))/10)*10
timeBy     <- timeTo/200
################  Prepare inputs and outputs ####################
non_negativity_cutoff <- 0
outFile <- "Exemplary Trees/pFitness.out.rds"
rho = as.numeric(rho)
d_t = as.numeric(d_t)
time_scale = as.numeric(time_scale)
nu <- replicate(length(b_rates), as.numeric(nu))
T_vector <- seq(from = as.numeric(timeFrom), to = as.numeric(timeTo), by = as.numeric(timeBy))
non_negativity_cutoff = as.numeric(non_negativity_cutoff)
```

### Call LeafRank

```{r}
outcome = ith.Fitness(phy, outFile, rho, d_t, time_scale, b_rates, d_rates, nu, T_vector, non_negativity_cutoff)
```

## Plot and analyze prediction

```{r}
Results       <- readRDS("Exemplary Trees/pFitness.out.rds")
phy           <- Results$phylo
TrueFitness   <- b_rates[as.numeric(phy$fitness$V1)]
PredFitness   <- Results$meanFitness[1:length(phy$tip.label)]
True_Pred_cor <- cor(TrueFitness, PredFitness, method = "spearman")

True_ring <- tibble(
  label = phy$tip.label,
  fitness = TrueFitness
)
Pred_ring <- tibble(
  label = phy$tip.label,
  fitness = PredFitness
)
  
plot_Pred <- ggtree(phy, layout = 'circular', size = 0.3) + 
             labs(title = paste0("TT ranking (rho: ",format(True_Pred_cor, nsmall = 4),")")) +
             theme(
               legend.position = "right",
               plot.title = element_text(hjust = 0.5),
               legend.key.size = unit(0.2, "cm"),
               plot.margin = unit(c(0,0,0,0), "cm")
               ) + 
             geom_fruit(
               data = Pred_ring,
               geom = geom_bar,
               mapping = aes(y = label, x = fitness, fill = fitness),
               orientation = "y",
               stat = "identity",
               width = 0.3
               ) +
             scale_fill_gradient(
               low = "#93C477", 
               high = "#1F78B4"
               ) +
             guides(
               fill = guide_colorbar(order = 1), 
               color = guide_legend(order = 2)
               )
  
  

  
  
plot_True <- ggtree(phy, layout = 'circular', size = 0.3) + 
             labs(title = "True ranking") +
             theme(
               legend.position = "right",
               plot.title = element_text(hjust = 0.5),
               legend.key.size = unit(0.2, "cm"),
               plot.margin = unit(c(0,0,0,0), "cm")
               ) + 
             geom_fruit(
               data = True_ring,
               geom = geom_bar,
               mapping = aes(y = label, x = fitness, fill = fitness),
               orientation = "y",
               stat = "identity",
               width = 0.3
               ) +
             scale_fill_gradient(
               low = "#93C477", 
               high = "#1F78B4"
               ) +
             guides(
               fill = guide_colorbar(order = 1), 
               color = guide_legend(order = 2)
               )

plots <- (plot_True|plot_Pred)

```


## Reconstructing ultrametric tree from Distance-matrix based tree (NJ/MEDICC2).

```{r}

# Prepared the MATLAB files for optimization
phy <- readRDS('Exemplary Trees/Tree-DM.rds')
tips_WGD <- phy$node_wgd
get_ultrametric_prepared (phy, tips_WGD, MAT_path = "MATLAB/DM-tree.mat")

# Access the MATLAB results and output the WGD tree
WGD_tree <- get_ultrametric(phy, MAT_path = "MATLAB/ultra-tree.csv", phy_path = "Exemplary Trees/Tree-WGD.rds")

```
